-- ============================================================
-- mmo_auth: аккаунты и аутентификация (изолированный периметр)
-- Этап 1: вход только через Telegram Mini App (initData).
-- ============================================================
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status      SMALLINT    NOT NULL DEFAULT 1,  -- 1 active, 2 frozen, 3 banned, 4 deleted
    country     TEXT,
    locale      TEXT        NOT NULL DEFAULT 'ru',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ
);

CREATE TABLE account_identities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT      NOT NULL REFERENCES accounts(id),
    provider    SMALLINT    NOT NULL,            -- 1 telegram, 2 email, 3 google, ...
    external_id TEXT        NOT NULL,            -- tg_user_id как текст
    raw_profile JSONB,
    linked_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, external_id)
);
CREATE INDEX ix_identities_account ON account_identities (account_id);

CREATE TABLE telegram_profiles (
    account_id    BIGINT      PRIMARY KEY REFERENCES accounts(id),
    tg_user_id    BIGINT      NOT NULL UNIQUE,
    username      TEXT,
    first_name    TEXT,
    photo_url     TEXT,
    language_code TEXT,
    is_tg_premium BOOLEAN     NOT NULL DEFAULT FALSE,
    allows_pm     BOOLEAN     NOT NULL DEFAULT FALSE,
    last_auth_at  TIMESTAMPTZ
);

-- Защита от replay подписанного initData
CREATE TABLE auth_nonces (
    init_data_hash TEXT        PRIMARY KEY,
    auth_date      TIMESTAMPTZ NOT NULL,
    used_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_auth_nonces_used ON auth_nonces (used_at); -- для чистки воркером

CREATE TABLE sessions (
    token_hash   TEXT        PRIMARY KEY,        -- сам токен не хранится
    account_id   BIGINT      NOT NULL REFERENCES accounts(id),
    character_id BIGINT,
    ip           INET,
    user_agent   TEXT,
    platform     SMALLINT    NOT NULL DEFAULT 1, -- 1 telegram_webapp, 2 web, ...
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,
    revoked_at   TIMESTAMPTZ
);
CREATE INDEX ix_sessions_account ON sessions (account_id);

CREATE TABLE login_history (
    account_id  BIGINT,
    ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip          INET,
    platform    SMALLINT,
    fingerprint TEXT,
    result      SMALLINT NOT NULL   -- 1 ok, 2 bad_signature, 3 expired, 4 banned
) PARTITION BY RANGE (ts);
CREATE TABLE login_history_default PARTITION OF login_history DEFAULT;
CREATE INDEX ix_login_history_acc ON login_history (account_id, ts);

CREATE TABLE account_sanctions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT      NOT NULL REFERENCES accounts(id),
    type        SMALLINT    NOT NULL,  -- 1 ban, 2 trade_ban, 3 chat_ban, 4 battle_ban
    reason      TEXT,
    evidence_ref TEXT,
    issued_by   BIGINT,
    starts_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    ends_at     TIMESTAMPTZ,           -- NULL = навсегда
    revoked_at  TIMESTAMPTZ,
    revoked_by  BIGINT
);
CREATE INDEX ix_sanctions_account ON account_sanctions (account_id) WHERE revoked_at IS NULL;

CREATE TABLE device_fingerprints (
    account_id BIGINT      NOT NULL REFERENCES accounts(id),
    fp_hash    TEXT        NOT NULL,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, fp_hash)
);
CREATE INDEX ix_fp_hash ON device_fingerprints (fp_hash);

CREATE TABLE account_links (
    account_a  BIGINT      NOT NULL,
    account_b  BIGINT      NOT NULL,
    link_type  SMALLINT    NOT NULL,  -- 1 same_ip, 2 same_device
    score      INT         NOT NULL DEFAULT 0,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (account_a, account_b, link_type),
    CHECK (account_a < account_b)
);

-- Этап 1: пустуют, включаются при добавлении входа по почте
CREATE TABLE account_credentials (
    account_id          BIGINT PRIMARY KEY REFERENCES accounts(id),
    password_hash       TEXT NOT NULL,           -- Argon2id
    password_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    must_change         BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE account_2fa (
    account_id             BIGINT PRIMARY KEY REFERENCES accounts(id),
    method                 SMALLINT NOT NULL,    -- 1 totp, 2 email
    secret_encrypted       TEXT,
    backup_codes_encrypted TEXT,
    enabled_at             TIMESTAMPTZ
);
CREATE TABLE password_resets (
    token_hash TEXT PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ
);
CREATE TABLE email_verifications (
    token_hash TEXT PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    email      CITEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ
);

-- ---------- права ----------
GRANT CONNECT ON DATABASE mmo_auth TO auth_svc;
GRANT USAGE ON SCHEMA public TO auth_svc;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO auth_svc;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO auth_svc;
-- login_history — append-only даже для auth-сервиса
REVOKE UPDATE ON login_history, login_history_default FROM auth_svc;
-- nonces можно чистить только воркером под суперпользователем; DELETE никому не выдаём
