-- ============================================================
-- mmo_billing: платежи (изолированный периметр)
-- Этап 1: только Telegram Stars (provider=1, currency='XTR').
-- ============================================================
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT      NOT NULL,
    provider    SMALLINT    NOT NULL DEFAULT 1,  -- 1 telegram_stars
    external_id TEXT        NOT NULL UNIQUE,     -- telegram_payment_charge_id:
                                                 -- обязателен для refundStarPayment
    amount      BIGINT      NOT NULL CHECK (amount > 0),
    currency    TEXT        NOT NULL DEFAULT 'XTR',
    status      SMALLINT    NOT NULL DEFAULT 1,  -- 1 pending, 2 paid, 3 failed,
                                                 -- 4 refunded, 5 chargeback
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at     TIMESTAMPTZ
);
CREATE INDEX ix_payments_account ON payments (account_id, created_at);

-- Сырые апдейты бота (pre_checkout_query, successful_payment, refunded_payment)
CREATE TABLE payment_webhooks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    SMALLINT    NOT NULL DEFAULT 1,
    update_id   BIGINT,
    payload     JSONB       NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE shop_products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku      TEXT     NOT NULL UNIQUE,
    type     SMALLINT NOT NULL,         -- 1 валюта, 2 предмет, 3 премиум, 4 набор
    title    TEXT     NOT NULL,
    price    BIGINT   NOT NULL CHECK (price > 0),  -- в Stars
    contents JSONB    NOT NULL,         -- что выдать (валюты/шаблоны предметов)
    active   BOOLEAN  NOT NULL DEFAULT TRUE,
    version  INT      NOT NULL DEFAULT 1
);

CREATE TABLE shop_purchases (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key UUID        NOT NULL UNIQUE,
    account_id      BIGINT      NOT NULL,
    character_id    BIGINT,
    product_id      BIGINT      NOT NULL REFERENCES shop_products(id),
    payment_id      BIGINT      REFERENCES payments(id),
    status          SMALLINT    NOT NULL DEFAULT 1, -- 1 pending (pre_checkout),
                                                    -- 2 paid, 3 delivered, 4 failed
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at    TIMESTAMPTZ,
    delivery_ref    BIGINT                          -- id системного письма с товаром
);
CREATE INDEX ix_purchases_account ON shop_purchases (account_id, created_at);

CREATE TABLE premium_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT      NOT NULL,
    plan       SMALLINT    NOT NULL DEFAULT 1,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    auto_renew BOOLEAN     NOT NULL DEFAULT FALSE,
    source_purchase_id BIGINT REFERENCES shop_purchases(id)
);
CREATE INDEX ix_premium_account ON premium_subscriptions (account_id, expires_at);

CREATE TABLE promo_codes (
    code              CITEXT   PRIMARY KEY,
    rewards           JSONB    NOT NULL,
    max_uses          INT,
    per_account_limit INT      NOT NULL DEFAULT 1,
    uses              INT      NOT NULL DEFAULT 0,
    expires_at        TIMESTAMPTZ
);

CREATE TABLE promo_redemptions (
    code        CITEXT      NOT NULL REFERENCES promo_codes(code),
    account_id  BIGINT      NOT NULL,
    redeemed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (code, account_id)
);

CREATE TABLE refunds (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id  BIGINT      NOT NULL REFERENCES payments(id),
    reason      TEXT,
    revoked     JSONB,                  -- что отозвано у игрока
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    external_ref TEXT                   -- ответ refundStarPayment
);

-- ---------- права ----------
GRANT CONNECT ON DATABASE mmo_billing TO billing_svc;
GRANT USAGE ON SCHEMA public TO billing_svc;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO billing_svc;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO billing_svc;
-- журналы append-only
REVOKE UPDATE ON payment_webhooks, refunds FROM billing_svc;
